const symbol = {
    carboneum: {
        "LET/BTC": {"huobi": "LETBTC"},
        "MTH/BTC": {"binance": "MTHBTC", "kucoin": "MTH-BTC"},
        "SNOV/BTC": {"kucoin": "SNOV-BTC"},
        "GAT/BTC": {"kucoin": "GAT-BTC"},
        "NANO/BTC": {"binance": "NANOBTC"},
        "GNT/BNB": {"binance": "GNTBNB"},
        "CAPP/BTC": {"kucoin": "CAPP-BTC"},
        "WAVES/ETH": {"binance": "WAVESETH"},
        "KICK/BTC": {"kucoin": "KICK-BTC"},
        "KCS/BTC": {"kucoin": "KCS-BTC"},
        "SPHTX/BTC": {"kucoin": "SPHTX-BTC"},
        "GRS/BTC": {"binance": "GRSBTC"},
        "DADI/ETH": {"kucoin": "DADI-ETH"},
        "HPB/BTC": {"kucoin": "HPB-BTC"},
        "NAS/ETH": {"huobi": "NASETH"},
        "POA/ETH": {"binance": "POAETH"},
        "BTC/HYP": {"bx": "13"},
        "IOST/USDT": {"huobi": "IOSTUSDT"},
        "TNB/ETH": {"binance": "TNBETH", "huobi": "TNBETH"},
        "EBTC/ETH": {"kucoin": "EBTC-ETH"},
        "SHL/ETH": {"kucoin": "SHL-ETH"},
        "NAS/USDT": {"huobi": "NASUSDT"},
        "SUB/ETH": {"binance": "SUBETH", "kucoin": "SUB-ETH"},
        "BTC/ZEC": {"bx": "8"},
        "BCH/KCS": {"kucoin": "BCH-KCS"},
        "AION/BNB": {"binance": "AIONBNB"},
        "CAPP/ETH": {"kucoin": "CAPP-ETH"},
        "RPX/BTC": {"binance": "RPXBTC", "huobi": "RPXBTC", "kucoin": "RPX-BTC"},
        "OAX/BTC": {"binance": "OAXBTC"},
        "CAN/ETH": {"kucoin": "CAN-ETH"},
        "EOS/ETH": {"binance": "EOSETH", "huobi": "EOSETH", "kucoin": "EOS-ETH"},
        "SMT/ETH": {"huobi": "SMTETH"},
        "YOYO/BTC": {"binance": "YOYOBTC"},
        "VIB/ETH": {"binance": "VIBETH"},
        "CHP/ETH": {"kucoin": "CHP-ETH"},
        "PARETO/BTC": {"kucoin": "PARETO-BTC"},
        "EVX/ETH": {"binance": "EVXETH", "huobi": "EVXETH", "kucoin": "EVX-ETH"},
        "AMB/ETH": {"binance": "AMBETH", "kucoin": "AMB-ETH"},
        "GAS/KCS": {"kucoin": "GAS-KCS"},
        "STK/BTC": {"huobi": "STKBTC", "kucoin": "STK-BTC"},
        "BTS/ETH": {"binance": "BTSETH", "huobi": "BTSETH"},
        "DRGN/BTC": {"kucoin": "DRGN-BTC"},
        "CAN/BTC": {"kucoin": "CAN-BTC"},
        "AION/BTC": {"binance": "AIONBTC", "kucoin": "AION-BTC"},
        "LSK/ETH": {"binance": "LSKETH", "huobi": "LSKETH"},
        "GLA/ETH": {"kucoin": "GLA-ETH"},
        "ETC/KCS": {"kucoin": "ETC-KCS"},
        "KNC/BTC": {"binance": "KNCBTC", "huobi": "KNCBTC", "kucoin": "KNC-BTC"},
        "THB/BCH": {"bx": "27"},
        "ZLA/BTC": {"huobi": "ZLABTC"},
        "ELF/ETH": {"binance": "ELFETH", "huobi": "ELFETH", "kucoin": "ELF-ETH"},
        "NULS/BNB": {"binance": "NULSBNB"},
        "XEM/BTC": {"binance": "XEMBTC", "huobi": "XEMBTC"},
        "QTUM/ETH": {"binance": "QTUMETH", "huobi": "QTUMETH"},
        "CXO/BTC": {"kucoin": "CXO-BTC"},
        "NEO/USDT": {"binance": "NEOUSDT", "huobi": "NEOUSDT", "kucoin": "NEO-USDT"},
        "ONION/BTC": {"kucoin": "ONION-BTC"},
        "ONT/BNB": {"binance": "ONTBNB"},
        "BCPT/BNB": {"binance": "BCPTBNB"},
        "BAT/BTC": {"binance": "BATBTC", "huobi": "BATBTC"},
        "XLR/ETH": {"kucoin": "XLR-ETH"},
        "POE/ETH": {"binance": "POEETH", "kucoin": "POE-ETH"},
        "BTC/DOG": {"bx": "4"},
        "BQX/ETH": {"binance": "BQXETH"},
        "ITC/USDT": {"huobi": "ITCUSDT"},
        "POLY/ETH": {"kucoin": "POLY-ETH"},
        "THETA/ETH": {"huobi": "THETAETH"},
        "NEO/ETH": {"binance": "NEOETH", "kucoin": "NEO-ETH"},
        "ELIX/BTC": {"kucoin": "ELIX-BTC"},
        "ETC/BTC": {"binance": "ETCBTC", "huobi": "ETCBTC", "kucoin": "ETC-BTC"},
        "AGI/BTC": {"kucoin": "AGI-BTC"},
        "FLIXX/ETH": {"kucoin": "FLIXX-ETH"},
        "ETN/ETH": {"kucoin": "ETN-ETH"},
        "DRGN/NEO": {"kucoin": "DRGN-NEO"},
        "TNT/BTC": {"binance": "TNTBTC", "huobi": "TNTBTC"},
        "UTK/ETH": {"huobi": "UTKETH", "kucoin": "UTK-ETH"},
        "BNTY/ETH": {"kucoin": "BNTY-ETH"},
        "BCPT/ETH": {"binance": "BCPTETH", "kucoin": "BCPT-ETH"},
        "INS/BTC": {"binance": "INSBTC", "kucoin": "INS-BTC"},
        "BLZ/BNB": {"binance": "BLZBNB"},
        "NEO/KCS": {"kucoin": "NEO-KCS"},
        "LINK/ETH": {"binance": "LINKETH", "huobi": "LINKETH"},
        "POWR/ETH": {"binance": "POWRETH", "huobi": "POWRETH", "kucoin": "POWR-ETH"},
        "BTM/USDT": {"huobi": "BTMUSDT"},
        "EKO/BTC": {"huobi": "EKOBTC"},
        "IHT/BTC": {"kucoin": "IHT-BTC"},
        "TKY/ETH": {"kucoin": "TKY-ETH"},
        "OCN/BTC": {"huobi": "OCNBTC", "kucoin": "OCN-BTC"},
        "CAG/BTC": {"kucoin": "CAG-BTC"},
        "WAVES/BNB": {"binance": "WAVESBNB"},
        "LSK/BTC": {"binance": "LSKBTC", "huobi": "LSKBTC"},
        "CS/USDT": {"kucoin": "CS-USDT"},
        "WAN/BNB": {"binance": "WANBNB"},
        "XVG/ETH": {"binance": "XVGETH"},
        "GTO/BNB": {"binance": "GTOBNB"},
        "PURA/ETH": {"kucoin": "PURA-ETH"},
        "TIO/BTC": {"kucoin": "TIO-BTC"},
        "DRGN/USDT": {"kucoin": "DRGN-USDT"},
        "ONT/BTC": {"binance": "ONTBTC", "huobi": "ONTBTC", "kucoin": "ONT-BTC"},
        "DNA/BTC": {"kucoin": "DNA-BTC"},
        "MWAT/BTC": {"kucoin": "MWAT-BTC"},
        "THB/EVX": {"bx": "28"},
        "DEB/BTC": {"kucoin": "DEB-BTC"},
        "KMD/BTC": {"binance": "KMDBTC"},
        "EVX/BTC": {"binance": "EVXBTC", "huobi": "EVXBTC", "kucoin": "EVX-BTC"},
        "BNB/ETH": {"binance": "BNBETH"},
        "KMD/ETH": {"binance": "KMDETH"},
        "R/ETH": {"kucoin": "R-ETH"},
        "STX/ETH": {"kucoin": "STX-ETH"},
        "EDU/ETH": {"huobi": "EDUETH"},
        "VIA/BNB": {"binance": "VIABNB"},
        "ADA/BNB": {"binance": "ADABNB"},
        "DGD/ETH": {"binance": "DGDETH", "huobi": "DGDETH"},
        "TIO/ETH": {"kucoin": "TIO-ETH"},
        "PAY/BTC": {"huobi": "PAYBTC", "kucoin": "PAY-BTC"},
        "GNX/BTC": {"huobi": "GNXBTC"},
        "BLZ/ETH": {"binance": "BLZETH", "huobi": "BLZETH"},
        "WICC/ETH": {"huobi": "WICCETH"},
        "ADB/ETH": {"kucoin": "ADB-ETH"},
        "SUB/BTC": {"binance": "SUBBTC", "kucoin": "SUB-BTC"},
        "IHT/ETH": {"kucoin": "IHT-ETH"},
        "SWFTC/ETH": {"huobi": "SWFTCETH"},
        "THB/XZC": {"bx": "29"},
        "TNC/BTC": {"kucoin": "TNC-BTC"},
        "NULS/BTC": {"binance": "NULSBTC", "kucoin": "NULS-BTC"},
        "QTUM/USDT": {"binance": "QTUMUSDT", "huobi": "QTUMUSDT"},
        "BRD/BTC": {"binance": "BRDBTC", "kucoin": "BRD-BTC"},
        "DAT/BTC": {"huobi": "DATBTC", "kucoin": "DAT-BTC"},
        "SPF/ETH": {"kucoin": "SPF-ETH"},
        "DTA/BTC": {"huobi": "DTABTC", "kucoin": "DTA-BTC"},
        "XZC/BTC": {"binance": "XZCBTC"},
        "VIBE/ETH": {"binance": "VIBEETH"},
        "STEEM/BTC": {"binance": "STEEMBTC", "huobi": "STEEMBTC"},
        "LTC/BNB": {"binance": "LTCBNB"},
        "BTS/BNB": {"binance": "BTSBNB"},
        "ADX/ETH": {"binance": "ADXETH", "huobi": "ADXETH"},
        "BTS/USDT": {"huobi": "BTSUSDT"},
        "ABT/BTC": {"huobi": "ABTBTC", "kucoin": "ABT-BTC"},
        "MDS/USDT": {"huobi": "MDSUSDT"},
        "SMT/BTC": {"huobi": "SMTBTC"},
        "BOS/BTC": {"kucoin": "BOS-BTC"},
        "VIB/BTC": {"binance": "VIBBTC"},
        "MOD/BTC": {"binance": "MODBTC", "kucoin": "MOD-BTC"},
        "FUEL/ETH": {"binance": "FUELETH"},
        "STEEM/BNB": {"binance": "STEEMBNB"},
        "ENG/ETH": {"binance": "ENGETH", "huobi": "ENGETH"},
        "CAT/ETH": {"kucoin": "CAT-ETH"},
        "DENT/ETH": {"kucoin": "DENT-ETH"},
        "PURA/BTC": {"kucoin": "PURA-BTC"},
        "TNC/ETH": {"kucoin": "TNC-ETH"},
        "SNT/ETH": {"binance": "SNTETH", "kucoin": "SNT-ETH"},
        "TKY/USDT": {"kucoin": "TKY-USDT"},
        "STK/ETH": {"huobi": "STKETH", "kucoin": "STK-ETH"},
        "POLY/BTC": {"kucoin": "POLY-BTC"},
        "GAS/ETH": {"huobi": "GASETH"},
        "ETC/ETH": {"binance": "ETCETH", "kucoin": "ETC-ETH"},
        "TRIG/BNB": {"binance": "TRIGBNB"},
        "ETH/BTC": {"binance": "ETHBTC", "huobi": "ETHBTC", "kucoin": "ETH-BTC", "bx": "20"},
        "CVC/BTC": {"huobi": "CVCBTC", "kucoin": "CVC-BTC"},
        "ZEN/ETH": {"binance": "ZENETH"},
        "TNB/BTC": {"binance": "TNBBTC", "huobi": "TNBBTC"},
        "PRL/NEO": {"kucoin": "PRL-NEO"},
        "XRP/BTC": {"binance": "XRPBTC", "huobi": "XRPBTC"},
        "THB/REP": {"bx": "23"},
        "GAS/BTC": {"binance": "GASBTC", "huobi": "GASBTC", "kucoin": "GAS-BTC"},
        "POA/BNB": {"binance": "POABNB"},
        "WINGS/ETH": {"binance": "WINGSETH"},
        "EDU/BTC": {"huobi": "EDUBTC"},
        "AMB/BNB": {"binance": "AMBBNB"},
        "TOPC/ETH": {"huobi": "TOPCETH"},
        "BRD/BNB": {"binance": "BRDBNB"},
        "YEE/BTC": {"huobi": "YEEBTC"},
        "TRIG/BTC": {"binance": "TRIGBTC"},
        "LA/BTC": {"kucoin": "LA-BTC"},
        "UTK/BTC": {"huobi": "UTKBTC", "kucoin": "UTK-BTC"},
        "XZC/ETH": {"binance": "XZCETH"},
        "DEB/ETH": {"kucoin": "DEB-ETH"},
        "HKN/BTC": {"kucoin": "HKN-BTC"},
        "NANO/ETH": {"binance": "NANOETH"},
        "WAVES/BTC": {"binance": "WAVESBTC"},
        "BIFI/BTC": {"huobi": "BIFIBTC"},
        "TUSD/BNB": {"binance": "TUSDBNB"},
        "LOOM/ETH": {"binance": "LOOMETH", "kucoin": "LOOM-ETH"},
        "GNT/ETH": {"binance": "GNTETH", "huobi": "GNTETH"},
        "FLIXX/BTC": {"kucoin": "FLIXX-BTC"},
        "ACT/BTC": {"huobi": "ACTBTC", "kucoin": "ACT-BTC"},
        "RHOC/BTC": {"kucoin": "RHOC-BTC"},
        "GVT/BTC": {"binance": "GVTBTC", "kucoin": "GVT-BTC"},
        "THB/BTC": {"bx": "1"},
        "THB/OMG": {"bx": "26"},
        "EXY/BTC": {"kucoin": "EXY-BTC"},
        "ARK/BTC": {"binance": "ARKBTC"},
        "PIVX/BNB": {"binance": "PIVXBNB"},
        "PRL/ETH": {"kucoin": "PRL-ETH"},
        "FUN/ETH": {"binance": "FUNETH"},
        "ELA/BTC": {"huobi": "ELABTC"},
        "COFI/ETH": {"kucoin": "COFI-ETH"},
        "MEET/BTC": {"huobi": "MEETBTC"},
        "ICX/BNB": {"binance": "ICXBNB"},
        "ZLA/ETH": {"huobi": "ZLAETH"},
        "BAT/BNB": {"binance": "BATBNB"},
        "AE/ETH": {"binance": "AEETH"},
        "DASH/ETH": {"binance": "DASHETH", "kucoin": "DASH-ETH"},
        "LBA/ETH": {"huobi": "LBAETH"},
        "SOC/ETH": {"huobi": "SOCETH"},
        "ICN/ETH": {"binance": "ICNETH"},
        "R/BTC": {"kucoin": "R-BTC"},
        "XEM/USDT": {"huobi": "XEMUSDT"},
        "FUEL/BTC": {"binance": "FUELBTC"},
        "HKN/ETH": {"kucoin": "HKN-ETH"},
        "LEND/ETH": {"binance": "LENDETH", "kucoin": "LEND-ETH"},
        "EOS/USDT": {"huobi": "EOSUSDT", "kucoin": "EOS-USDT"},
        "LOOM/BTC": {"binance": "LOOMBTC", "kucoin": "LOOM-BTC"},
        "CLOAK/ETH": {"binance": "CLOAKETH"},
        "UKG/ETH": {"kucoin": "UKG-ETH"},
        "RUFF/BTC": {"huobi": "RUFFBTC"},
        "BAT/ETH": {"binance": "BATETH", "huobi": "BATETH"},
        "CTXC/BTC": {"huobi": "CTXCBTC"},
        "EKO/ETH": {"huobi": "EKOETH"},
        "TNC/NEO": {"kucoin": "TNC-NEO"},
        "BCD/ETH": {"binance": "BCDETH", "kucoin": "BCD-ETH"},
        "STEEM/ETH": {"binance": "STEEMETH", "huobi": "STEEMETH"},
        "EOS/BTC": {"binance": "EOSBTC", "huobi": "EOSBTC", "kucoin": "EOS-BTC"},
        "BCH/USDT": {"huobi": "BCHUSDT", "kucoin": "BCH-USDT"},
        "CS/ETH": {"kucoin": "CS-ETH"},
        "IOTA/BTC": {"binance": "IOTABTC", "huobi": "IOTABTC"},
        "VEN/USDT": {"huobi": "VENUSDT"},
        "STORM/BTC": {"binance": "STORMBTC"},
        "MTN/ETH": {"huobi": "MTNETH", "kucoin": "MTN-ETH"},
        "DATX/ETH": {"kucoin": "DATX-ETH"},
        "BCPT/BTC": {"binance": "BCPTBTC", "kucoin": "BCPT-BTC"},
        "DASH/USDT": {"huobi": "DASHUSDT"},
        "ADA/BTC": {"binance": "ADABTC", "huobi": "ADABTC"},
        "XMR/ETH": {"binance": "XMRETH"},
        "BTC/LTC": {"bx": "2"},
        "LALA/ETH": {"kucoin": "LALA-ETH"},
        "NEBL/ETH": {"binance": "NEBLETH", "kucoin": "NEBL-ETH"},
        "BTS/BTC": {"binance": "BTSBTC", "huobi": "BTSBTC"},
        "MTL/BTC": {"binance": "MTLBTC", "huobi": "MTLBTC"},
        "XLM/ETH": {"binance": "XLMETH"},
        "COV/ETH": {"kucoin": "COV-ETH"},
        "ONT/USDT": {"huobi": "ONTUSDT"},
        "MDA/ETH": {"binance": "MDAETH"},
        "MDS/BTC": {"huobi": "MDSBTC"},
        "DOCK/ETH": {"kucoin": "DOCK-ETH"},
        "HAV/ETH": {"kucoin": "HAV-ETH"},
        "SALT/ETH": {"binance": "SALTETH", "huobi": "SALTETH"},
        "CND/ETH": {"binance": "CNDETH"},
        "ZEN/BTC": {"binance": "ZENBTC"},
        "DOCK/BTC": {"kucoin": "DOCK-BTC"},
        "CTXC/USDT": {"huobi": "CTXCUSDT"},
        "SNM/ETH": {"binance": "SNMETH", "kucoin": "SNM-ETH"},
        "LBA/BTC": {"huobi": "LBABTC"},
        "KEY/ETH": {"kucoin": "KEY-ETH"},
        "ING/ETH": {"kucoin": "ING-ETH"},
        "DGB/ETH": {"kucoin": "DGB-ETH"},
        "QSP/BTC": {"binance": "QSPBTC", "huobi": "QSPBTC", "kucoin": "QSP-BTC"},
        "ARN/BTC": {"binance": "ARNBTC", "kucoin": "ARN-BTC"},
        "NCASH/BTC": {"binance": "NCASHBTC"},
        "GNT/USDT": {"huobi": "GNTUSDT"},
        "ZRX/ETH": {"binance": "ZRXETH", "huobi": "ZRXETH"},
        "DADI/BTC": {"kucoin": "DADI-BTC"},
        "ACAT/BTC": {"kucoin": "ACAT-BTC"},
        "NEO/BNB": {"binance": "NEOBNB"},
        "BTM/ETH": {"huobi": "BTMETH", "kucoin": "BTM-ETH"},
        "BTC/PND": {"bx": "14"},
        "VEN/ETH": {"binance": "VENETH", "huobi": "VENETH", "kucoin": "VEN-ETH"},
        "WAN/ETH": {"binance": "WANETH", "huobi": "WANETH", "kucoin": "WAN-ETH"},
        "MAN/BTC": {"kucoin": "MAN-BTC"},
        "ETN/BTC": {"kucoin": "ETN-BTC"},
        "ONT/ETH": {"binance": "ONTETH", "huobi": "ONTETH", "kucoin": "ONT-ETH"},
        "REQ/BTC": {"binance": "REQBTC", "huobi": "REQBTC", "kucoin": "REQ-BTC"},
        "ARY/BTC": {"kucoin": "ARY-BTC"},
        "ZPT/NEO": {"kucoin": "ZPT-NEO"},
        "TOPC/BTC": {"huobi": "TOPCBTC"},
        "STX/BTC": {"kucoin": "STX-BTC"},
        "IOST/ETH": {"binance": "IOSTETH", "huobi": "IOSTETH", "kucoin": "IOST-ETH"},
        "AIDOC/BTC": {"huobi": "AIDOCBTC"},
        "COV/BTC": {"kucoin": "COV-BTC"},
        "DTA/ETH": {"huobi": "DTAETH", "kucoin": "DTA-ETH"},
        "LET/USDT": {"huobi": "LETUSDT"},
        "TUSD/BTC": {"binance": "TUSDBTC"},
        "CTXC/ETH": {"huobi": "CTXCETH"},
        "TEL/ETH": {"kucoin": "TEL-ETH"},
        "OST/BNB": {"binance": "OSTBNB"},
        "JNT/ETH": {"kucoin": "JNT-ETH"},
        "UKG/BTC": {"kucoin": "UKG-BTC"},
        "LYM/BTC": {"kucoin": "LYM-BTC"},
        "QLC/BNB": {"binance": "QLCBNB"},
        "CDT/ETH": {"binance": "CDTETH"},
        "DNA/ETH": {"kucoin": "DNA-ETH"},
        "RPX/NEO": {"kucoin": "RPX-NEO"},
        "REP/BTC": {"binance": "REPBTC"},
        "MCO/BTC": {"binance": "MCOBTC", "huobi": "MCOBTC"},
        "ONION/ETH": {"kucoin": "ONION-ETH"},
        "XLM/BNB": {"binance": "XLMBNB"},
        "WTC/ETH": {"binance": "WTCETH"},
        "XRB/USDT": {"kucoin": "XRB-USDT"},
        "BTM/BTC": {"huobi": "BTMBTC", "kucoin": "BTM-BTC"},
        "MAN/ETH": {"kucoin": "MAN-ETH"},
        "BQX/BTC": {"binance": "BQXBTC"},
        "NCASH/ETH": {"binance": "NCASHETH"},
        "LTC/USDT": {"binance": "LTCUSDT", "huobi": "LTCUSDT", "kucoin": "LTC-USDT"},
        "MTX/BTC": {"huobi": "MTXBTC"},
        "ENG/BTC": {"binance": "ENGBTC", "huobi": "ENGBTC"},
        "LTC/BTC": {"binance": "LTCBTC", "huobi": "LTCBTC", "kucoin": "LTC-BTC"},
        "ELF/USDT": {"huobi": "ELFUSDT"},
        "NEBL/BNB": {"binance": "NEBLBNB"},
        "BCD/BTC": {"binance": "BCDBTC", "huobi": "BCDBTC", "kucoin": "BCD-BTC"},
        "MTH/ETH": {"binance": "MTHETH", "kucoin": "MTH-ETH"},
        "TNT/ETH": {"binance": "TNTETH", "huobi": "TNTETH"},
        "THB/GNO": {"bx": "24"},
        "REP/BNB": {"binance": "REPBNB"},
        "SNM/BTC": {"binance": "SNMBTC", "kucoin": "SNM-BTC"},
        "GTO/BTC": {"binance": "GTOBTC"},
        "ELF/BTC": {"binance": "ELFBTC", "huobi": "ELFBTC", "kucoin": "ELF-BTC"},
        "ELEC/BTC": {"kucoin": "ELEC-BTC"},
        "BFT/BTC": {"huobi": "BFTBTC"},
        "ADA/USDT": {"binance": "ADAUSDT", "huobi": "ADAUSDT"},
        "IOTA/ETH": {"binance": "IOTAETH", "huobi": "IOTAETH"},
        "NEBL/BTC": {"binance": "NEBLBTC", "kucoin": "NEBL-BTC"},
        "NEO/BTC": {"binance": "NEOBTC", "huobi": "NEOBTC", "kucoin": "NEO-BTC"},
        "ZRX/BTC": {"binance": "ZRXBTC", "huobi": "ZRXBTC"},
        "QLC/NEO": {"kucoin": "QLC-NEO"},
        "WPR/ETH": {"binance": "WPRETH", "huobi": "WPRETH", "kucoin": "WPR-ETH"},
        "BCC/BTC": {"binance": "BCCBTC"},
        "RPX/BNB": {"binance": "RPXBNB"},
        "AIX/BTC": {"kucoin": "AIX-BTC"},
        "APPC/BNB": {"binance": "APPCBNB"},
        "QSP/ETH": {"binance": "QSPETH", "huobi": "QSPETH", "kucoin": "QSP-ETH"},
        "TOMO/ETH": {"kucoin": "TOMO-ETH"},
        "QTUM/BNB": {"binance": "QTUMBNB"},
        "SHL/BTC": {"kucoin": "SHL-BTC"},
        "CS/BTC": {"kucoin": "CS-BTC"},
        "ELEC/ETH": {"kucoin": "ELEC-ETH"},
        "JNT/BTC": {"kucoin": "JNT-BTC"},
        "TIME/BTC": {"kucoin": "TIME-BTC"},
        "CHAT/ETH": {"binance": "CHATETH", "huobi": "CHATETH"},
        "APH/ETH": {"kucoin": "APH-ETH"},
        "BCN/BNB": {"binance": "BCNBNB"},
        "CND/BNB": {"binance": "CNDBNB"},
        "KICK/ETH": {"kucoin": "KICK-ETH"},
        "STRAT/BTC": {"binance": "STRATBTC"},
        "HT/USDT": {"huobi": "HTUSDT"},
        "CMT/ETH": {"binance": "CMTETH", "huobi": "CMTETH"},
        "BNB/BTC": {"binance": "BNBBTC"},
        "THB/LTC": {"bx": "30"},
        "AE/BTC": {"binance": "AEBTC"},
        "VIA/ETH": {"binance": "VIAETH"},
        "MWAT/ETH": {"kucoin": "MWAT-ETH"},
        "SALT/BTC": {"binance": "SALTBTC", "huobi": "SALTBTC"},
        "WABI/BTC": {"binance": "WABIBTC"},
        "HPB/ETH": {"kucoin": "HPB-ETH"},
        "ZEC/ETH": {"binance": "ZECETH"},
        "AIDOC/ETH": {"huobi": "AIDOCETH"},
        "WICC/BTC": {"huobi": "WICCBTC"},
        "FOTA/ETH": {"kucoin": "FOTA-ETH"},
        "MANA/BTC": {"binance": "MANABTC", "huobi": "MANABTC", "kucoin": "MANA-BTC"},
        "GAS/NEO": {"kucoin": "GAS-NEO"},
        "NAV/BTC": {"binance": "NAVBTC"},
        "HSR/BTC": {"binance": "HSRBTC", "huobi": "HSRBTC", "kucoin": "HSR-BTC"},
        "XMR/BTC": {"binance": "XMRBTC"},
        "POLL/BTC": {"kucoin": "POLL-BTC"},
        "IOST/BTC": {"binance": "IOSTBTC", "huobi": "IOSTBTC", "kucoin": "IOST-BTC"},
        "SNGLS/ETH": {"binance": "SNGLSETH"},
        "POWR/BTC": {"binance": "POWRBTC", "huobi": "POWRBTC", "kucoin": "POWR-BTC"},
        "CDT/BTC": {"binance": "CDTBTC"},
        "AST/ETH": {"binance": "ASTETH", "huobi": "ASTETH"},
        "IOTA/USDT": {"huobi": "IOTAUSDT"},
        "XRP/USDT": {"binance": "XRPUSDT", "huobi": "XRPUSDT"},
        "BTC/CPT": {"bx": "11"},
        "CND/BTC": {"binance": "CNDBTC"},
        "FOTA/BTC": {"kucoin": "FOTA-BTC"},
        "TRIG/ETH": {"binance": "TRIGETH"},
        "LOOM/BNB": {"binance": "LOOMBNB"},
        "NCASH/BNB": {"binance": "NCASHBNB"},
        "DATX/BTC": {"kucoin": "DATX-BTC"},
        "BNT/BTC": {"binance": "BNTBTC"},
        "RPX/KCS": {"kucoin": "RPX-KCS"},
        "SOC/BTC": {"huobi": "SOCBTC"},
        "MEET/ETH": {"huobi": "MEETETH"},
        "XLR/BTC": {"kucoin": "XLR-BTC"},
        "CV/ETH": {"kucoin": "CV-ETH"},
        "ACT/USDT": {"huobi": "ACTUSDT", "kucoin": "ACT-USDT"},
        "LINK/BTC": {"binance": "LINKBTC", "huobi": "LINKBTC"},
        "DBC/ETH": {"huobi": "DBCETH", "kucoin": "DBC-ETH"},
        "PARETO/ETH": {"kucoin": "PARETO-ETH"},
        "TRAC/BTC": {"kucoin": "TRAC-BTC"},
        "WAX/ETH": {"huobi": "WAXETH", "kucoin": "WAX-ETH"},
        "OMG/BTC": {"binance": "OMGBTC", "huobi": "OMGBTC", "kucoin": "OMG-BTC"},
        "SNGLS/BTC": {"binance": "SNGLSBTC"},
        "MDS/ETH": {"huobi": "MDSETH"},
        "AION/ETH": {"binance": "AIONETH", "kucoin": "AION-ETH"},
        "STORJ/USDT": {"huobi": "STORJUSDT"},
        "ELA/USDT": {"huobi": "ELAUSDT"},
        "ADX/BTC": {"binance": "ADXBTC", "huobi": "ADXBTC"},
        "BCX/BTC": {"huobi": "BCXBTC"},
        "BCC/USDT": {"binance": "BCCUSDT"},
        "TFL/BTC": {"kucoin": "TFL-BTC"},
        "DBC/BTC": {"huobi": "DBCBTC", "kucoin": "DBC-BTC"},
        "MCO/BNB": {"binance": "MCOBNB"},
        "DBC/NEO": {"kucoin": "DBC-NEO"},
        "PIVX/BTC": {"binance": "PIVXBTC"},
        "CVC/ETH": {"huobi": "CVCETH", "kucoin": "CVC-ETH"},
        "BCC/BNB": {"binance": "BCCBNB"},
        "HAT/BTC": {"kucoin": "HAT-BTC"},
        "LUN/BTC": {"binance": "LUNBTC", "huobi": "LUNBTC"},
        "TRX/BTC": {"binance": "TRXBTC", "huobi": "TRXBTC"},
        "QLC/ETH": {"binance": "QLCETH", "kucoin": "QLC-ETH"},
        "STORJ/ETH": {"binance": "STORJETH"},
        "KCS/ETH": {"kucoin": "KCS-ETH"},
        "VIA/BTC": {"binance": "VIABTC"},
        "VEN/BNB": {"binance": "VENBNB"},
        "CMT/BNB": {"binance": "CMTBNB"},
        "XRP/ETH": {"binance": "XRPETH"},
        "QASH/ETH": {"huobi": "QASHETH"},
        "REQ/ETH": {"binance": "REQETH", "huobi": "REQETH", "kucoin": "REQ-ETH"},
        "LA/ETH": {"kucoin": "LA-ETH"},
        "XVG/BTC": {"binance": "XVGBTC"},
        "DAT/ETH": {"huobi": "DATETH", "kucoin": "DAT-ETH"},
        "RLC/BNB": {"binance": "RLCBNB"},
        "TUSD/ETH": {"binance": "TUSDETH"},
        "BTC/XCN": {"bx": "15"},
        "AMB/BTC": {"binance": "AMBBTC", "kucoin": "AMB-BTC"},
        "LYM/ETH": {"kucoin": "LYM-ETH"},
        "DLT/ETH": {"binance": "DLTETH"},
        "MDA/BTC": {"binance": "MDABTC"},
        "YOYO/ETH": {"binance": "YOYOETH"},
        "LALA/BTC": {"kucoin": "LALA-BTC"},
        "OST/ETH": {"binance": "OSTETH", "huobi": "OSTETH"},
        "TFL/ETH": {"kucoin": "TFL-ETH"},
        "TOMO/BTC": {"kucoin": "TOMO-BTC"},
        "ENJ/BTC": {"binance": "ENJBTC", "kucoin": "ENJ-BTC"},
        "MOD/ETH": {"binance": "MODETH", "kucoin": "MOD-ETH"},
        "ZIL/BTC": {"binance": "ZILBTC", "huobi": "ZILBTC", "kucoin": "ZIL-BTC"},
        "BOS/ETH": {"kucoin": "BOS-ETH"},
        "QUN/ETH": {"huobi": "QUNETH"},
        "BTC/USDT": {"binance": "BTCUSDT", "huobi": "BTCUSDT", "kucoin": "BTC-USDT"},
        "SRN/ETH": {"huobi": "SRNETH", "kucoin": "SRN-ETH"},
        "THETA/USDT": {"huobi": "THETAUSDT"},
        "MANA/ETH": {"binance": "MANAETH", "huobi": "MANAETH", "kucoin": "MANA-ETH"},
        "DGD/BTC": {"binance": "DGDBTC", "huobi": "DGDBTC"},
        "DNT/ETH": {"binance": "DNTETH"},
        "BCN/BTC": {"binance": "BCNBTC"},
        "ETC/USDT": {"huobi": "ETCUSDT"},
        "POA/BTC": {"binance": "POABTC"},
        "STORM/BNB": {"binance": "STORMBNB"},
        "LOCI/BTC": {"kucoin": "LOCI-BTC"},
        "HST/BTC": {"kucoin": "HST-BTC"},
        "OPEN/BTC": {"kucoin": "OPEN-BTC"},
        "ADX/BNB": {"binance": "ADXBNB"},
        "BTC/FTC": {"bx": "6"},
        "QASH/BTC": {"huobi": "QASHBTC"},
        "DRGN/ETH": {"kucoin": "DRGN-ETH"},
        "FUN/BTC": {"binance": "FUNBTC"},
        "ING/BTC": {"kucoin": "ING-BTC"},
        "ACT/ETH": {"huobi": "ACTETH", "kucoin": "ACT-ETH"},
        "ZEC/BTC": {"binance": "ZECBTC", "huobi": "ZECBTC"},
        "TRX/ETH": {"binance": "TRXETH", "huobi": "TRXETH"},
        "BHC/BTC": {"kucoin": "BHC-BTC"},
        "SPF/BTC": {"kucoin": "SPF-BTC"},
        "SYS/ETH": {"binance": "SYSETH"},
        "PIVX/ETH": {"binance": "PIVXETH"},
        "MCO/ETH": {"binance": "MCOETH", "huobi": "MCOETH"},
        "ZIL/BNB": {"binance": "ZILBNB"},
        "RHOC/ETH": {"kucoin": "RHOC-ETH"},
        "HAV/USDT": {"kucoin": "HAV-USDT"},
        "DLT/BNB": {"binance": "DLTBNB"},
        "BFT/ETH": {"huobi": "BFTETH"},
        "RCN/ETH": {"binance": "RCNETH", "huobi": "RCNETH"},
        "BTC/XPY": {"bx": "17"},
        "GAT/ETH": {"kucoin": "GAT-ETH"},
        "XEM/ETH": {"binance": "XEMETH"},
        "XRB/ETH": {"kucoin": "XRB-ETH"},
        "OST/BTC": {"binance": "OSTBTC", "huobi": "OSTBTC"},
        "BNB/USDT": {"binance": "BNBUSDT"},
        "TRX/USDT": {"huobi": "TRXUSDT"},
        "ICN/BTC": {"binance": "ICNBTC"},
        "QSP/BNB": {"binance": "QSPBNB"},
        "THB/POW": {"bx": "31"},
        "VIBE/BTC": {"binance": "VIBEBTC"},
        "LTC/ETH": {"binance": "LTCETH", "kucoin": "LTC-ETH"},
        "WAX/BTC": {"huobi": "WAXBTC", "kucoin": "WAX-BTC"},
        "AST/BTC": {"binance": "ASTBTC", "huobi": "ASTBTC"},
        "PAY/ETH": {"huobi": "PAYETH", "kucoin": "PAY-ETH"},
        "BTC/XPM": {"bx": "7"},
        "POLL/ETH": {"kucoin": "POLL-ETH"},
        "MTL/ETH": {"binance": "MTLETH"},
        "AGI/ETH": {"kucoin": "AGI-ETH"},
        "GLA/BTC": {"kucoin": "GLA-BTC"},
        "XZC/BNB": {"binance": "XZCBNB"},
        "SMT/USDT": {"huobi": "SMTUSDT"},
        "HT/ETH": {"huobi": "HTETH"},
        "PPT/BTC": {"binance": "PPTBTC", "kucoin": "PPT-BTC"},
        "RLC/ETH": {"binance": "RLCETH"},
        "TEL/BTC": {"kucoin": "TEL-BTC"},
        "REP/ETH": {"binance": "REPETH"},
        "BTG/ETH": {"binance": "BTGETH", "kucoin": "BTG-ETH"},
        "RCN/BNB": {"binance": "RCNBNB"},
        "TKY/BTC": {"kucoin": "TKY-BTC"},
        "DTA/USDT": {"huobi": "DTAUSDT"},
        "COFI/BTC": {"kucoin": "COFI-BTC"},
        "DENT/BTC": {"kucoin": "DENT-BTC"},
        "SWFTC/BTC": {"huobi": "SWFTCBTC"},
        "THB/DAS": {"bx": "22"},
        "POWR/BNB": {"binance": "POWRBNB"},
        "LTC/NEO": {"kucoin": "LTC-NEO"},
        "EOS/NEO": {"kucoin": "EOS-NEO"},
        "OMG/USDT": {"huobi": "OMGUSDT"},
        "ZEC/USDT": {"huobi": "ZECUSDT"},
        "QLC/BTC": {"binance": "QLCBTC", "kucoin": "QLC-BTC"},
        "AXP/ETH": {"kucoin": "AXP-ETH"},
        "J8T/BTC": {"kucoin": "J8T-BTC"},
        "QUN/BTC": {"huobi": "QUNBTC"},
        "DLT/BTC": {"binance": "DLTBTC"},
        "THETA/BTC": {"huobi": "THETABTC"},
        "ICX/ETH": {"binance": "ICXETH", "huobi": "ICXETH"},
        "GNT/BTC": {"binance": "GNTBTC", "huobi": "GNTBTC"},
        "LYM/USDT": {"kucoin": "LYM-USDT"},
        "LSK/BNB": {"binance": "LSKBNB"},
        "SPHTX/ETH": {"kucoin": "SPHTX-ETH"},
        "WABI/ETH": {"binance": "WABIETH"},
        "BCC/ETH": {"binance": "BCCETH"},
        "OCN/ETH": {"huobi": "OCNETH", "kucoin": "OCN-ETH"},
        "SNC/BTC": {"huobi": "SNCBTC", "kucoin": "SNC-BTC"},
        "ZIL/ETH": {"binance": "ZILETH", "huobi": "ZILETH", "kucoin": "ZIL-ETH"},
        "RDN/BTC": {"binance": "RDNBTC", "huobi": "RDNBTC", "kucoin": "RDN-BTC"},
        "NAV/ETH": {"binance": "NAVETH"},
        "CLOAK/BTC": {"binance": "CLOAKBTC"},
        "RPX/ETH": {"binance": "RPXETH", "kucoin": "RPX-ETH"},
        "WINGS/BTC": {"binance": "WINGSBTC"},
        "BNTY/BTC": {"kucoin": "BNTY-BTC"},
        "NANO/BNB": {"binance": "NANOBNB"},
        "WPR/BTC": {"binance": "WPRBTC", "huobi": "WPRBTC", "kucoin": "WPR-BTC"},
        "ARN/ETH": {"binance": "ARNETH", "kucoin": "ARN-ETH"},
        "APPC/ETH": {"binance": "APPCETH", "huobi": "APPCETH"},
        "SNOV/ETH": {"kucoin": "SNOV-ETH"},
        "EDO/BTC": {"binance": "EDOBTC"},
        "GTO/ETH": {"binance": "GTOETH"},
        "WTC/BNB": {"binance": "WTCBNB"},
        "SYS/BTC": {"binance": "SYSBTC"},
        "BPT/ETH": {"kucoin": "BPT-ETH"},
        "RLC/BTC": {"binance": "RLCBTC"},
        "THB/XRP": {"bx": "25"},
        "THB/ETH": {"bx": "21"},
        "STORM/ETH": {"binance": "STORMETH"},
        "PRL/BTC": {"kucoin": "PRL-BTC"},
        "XLM/BTC": {"binance": "XLMBTC"},
        "KNC/ETH": {"binance": "KNCETH", "huobi": "KNCETH", "kucoin": "KNC-ETH"},
        "YOYO/BNB": {"binance": "YOYOBNB"},
        "QTUM/BTC": {"binance": "QTUMBTC", "huobi": "QTUMBTC", "kucoin": "QTUM-BTC"},
        "ARK/ETH": {"binance": "ARKETH"},
        "XEM/BNB": {"binance": "XEMBNB"},
        "XRB/BTC": {"kucoin": "XRB-BTC"},
        "SYS/BNB": {"binance": "SYSBNB"},
        "KEY/BTC": {"kucoin": "KEY-BTC"},
        "HSR/USDT": {"huobi": "HSRUSDT", "kucoin": "HSR-USDT"},
        "INS/ETH": {"binance": "INSETH", "kucoin": "INS-ETH"},
        "STRAT/ETH": {"binance": "STRATETH"},
        "EXY/ETH": {"kucoin": "EXY-ETH"},
        "PLAY/BTC": {"kucoin": "PLAY-BTC"},
        "WTC/BTC": {"binance": "WTCBTC", "kucoin": "WTC-BTC"},
        "GVT/ETH": {"binance": "GVTETH", "kucoin": "GVT-ETH"},
        "SRN/BTC": {"huobi": "SRNBTC", "kucoin": "SRN-BTC"},
        "BLZ/BTC": {"binance": "BLZBTC", "huobi": "BLZBTC"},
        "CHSB/ETH": {"kucoin": "CHSB-ETH"},
        "RDN/BNB": {"binance": "RDNBNB"},
        "HAT/ETH": {"kucoin": "HAT-ETH"},
        "NAS/BTC": {"huobi": "NASBTC"},
        "J8T/ETH": {"kucoin": "J8T-ETH"},
        "STEEM/USDT": {"huobi": "STEEMUSDT"},
        "ELIX/ETH": {"kucoin": "ELIX-ETH"},
        "CVC/USDT": {"huobi": "CVCUSDT"},
        "GXS/ETH": {"binance": "GXSETH"},
        "RDN/ETH": {"binance": "RDNETH", "huobi": "RDNETH", "kucoin": "RDN-ETH"},
        "XAS/BTC": {"kucoin": "XAS-BTC"},
        "CAT/BTC": {"kucoin": "CAT-BTC"},
        "ZEN/BNB": {"binance": "ZENBNB"},
        "APPC/BTC": {"binance": "APPCBTC", "huobi": "APPCBTC"},
        "PPT/ETH": {"binance": "PPTETH", "kucoin": "PPT-ETH"},
        "BCH/BTC": {"huobi": "BCHBTC", "kucoin": "BCH-BTC"},
        "WAN/BTC": {"binance": "WANBTC", "huobi": "WANBTC", "kucoin": "WAN-BTC"},
        "MTN/BTC": {"huobi": "MTNBTC", "kucoin": "MTN-BTC"},
        "HSR/ETH": {"binance": "HSRETH", "huobi": "HSRETH", "kucoin": "HSR-ETH"},
        "ABT/ETH": {"huobi": "ABTETH", "kucoin": "ABT-ETH"},
        "ARY/ETH": {"kucoin": "ARY-ETH"},
        "GRS/ETH": {"binance": "GRSETH"},
        "LRC/BTC": {"binance": "LRCBTC"},
        "BRD/ETH": {"binance": "BRDETH", "kucoin": "BRD-ETH"},
        "CV/BTC": {"kucoin": "CV-BTC"},
        "CHP/BTC": {"kucoin": "CHP-BTC"},
        "VEN/BTC": {"binance": "VENBTC", "huobi": "VENBTC", "kucoin": "VEN-BTC"},
        "AXP/BTC": {"kucoin": "AXP-BTC"},
        "PROPY/BTC": {"huobi": "PROPYBTC"},
        "LUN/ETH": {"binance": "LUNETH", "huobi": "LUNETH"},
        "XAS/ETH": {"kucoin": "XAS-ETH"},
        "SNT/BTC": {"binance": "SNTBTC", "huobi": "SNTBTC", "kucoin": "SNT-BTC"},
        "BTC/PPC": {"bx": "5"},
        "LEND/BTC": {"binance": "LENDBTC", "kucoin": "LEND-BTC"},
        "POE/BTC": {"binance": "POEBTC", "kucoin": "POE-BTC"},
        "ELA/ETH": {"huobi": "ELAETH"},
        "SBTC/BTC": {"huobi": "SBTCBTC"},
        "APH/BTC": {"kucoin": "APH-BTC"},
        "CAG/ETH": {"kucoin": "CAG-ETH"},
        "ITC/ETH": {"huobi": "ITCETH", "kucoin": "ITC-ETH"},
        "PBL/BTC": {"kucoin": "PBL-BTC"},
        "BPT/BTC": {"kucoin": "BPT-BTC"},
        "EBTC/BTC": {"kucoin": "EBTC-BTC"},
        "OAX/ETH": {"binance": "OAXETH"},
        "HT/BTC": {"huobi": "HTBTC"},
        "NULS/ETH": {"binance": "NULSETH", "kucoin": "NULS-ETH"},
        "BTC/LEO": {"bx": "18"},
        "IOTA/BNB": {"binance": "IOTABNB"},
        "ENJ/ETH": {"binance": "ENJETH", "kucoin": "ENJ-ETH"},
        "PBL/ETH": {"kucoin": "PBL-ETH"},
        "OMG/ETH": {"binance": "OMGETH", "huobi": "OMGETH", "kucoin": "OMG-ETH"},
        "BTC/NMC": {"bx": "3"},
        "RUFF/ETH": {"huobi": "RUFFETH"},
        "DGB/BTC": {"kucoin": "DGB-BTC"},
        "ACAT/ETH": {"kucoin": "ACAT-ETH"},
        "DASH/BTC": {"binance": "DASHBTC", "huobi": "DASHBTC", "kucoin": "DASH-BTC"},
        "BCH/ETH": {"kucoin": "BCH-ETH"},
        "OPEN/ETH": {"kucoin": "OPEN-ETH"},
        "STORJ/BTC": {"binance": "STORJBTC", "huobi": "STORJBTC"},
        "CHSB/BTC": {"kucoin": "CHSB-BTC"},
        "SOC/USDT": {"huobi": "SOCUSDT"},
        "SNC/ETH": {"huobi": "SNCETH", "kucoin": "SNC-ETH"},
        "ADA/ETH": {"binance": "ADAETH", "huobi": "ADAETH"},
        "ZPT/BTC": {"kucoin": "ZPT-BTC"},
        "LRC/ETH": {"binance": "LRCETH"},
        "GXS/BTC": {"binance": "GXSBTC"},
        "ONT/NEO": {"kucoin": "ONT-NEO"},
        "TKY/NEO": {"kucoin": "TKY-NEO"},
        "BTG/BTC": {"binance": "BTGBTC", "huobi": "BTGBTC", "kucoin": "BTG-BTC"},
        "WABI/BNB": {"binance": "WABIBNB"},
        "ZIL/USDT": {"huobi": "ZILUSDT"},
        "PLAY/ETH": {"kucoin": "PLAY-ETH"},
        "ICX/BTC": {"binance": "ICXBTC", "huobi": "ICXBTC"},
        "TRAC/ETH": {"kucoin": "TRAC-ETH"},
        "BTC/ZET": {"bx": "9"},
        "GNX/ETH": {"huobi": "GNXETH"},
        "AIX/ETH": {"kucoin": "AIX-ETH"},
        "RCN/BTC": {"binance": "RCNBTC", "huobi": "RCNBTC"},
        "KCS/USDT": {"kucoin": "KCS-USDT"},
        "ITC/BTC": {"huobi": "ITCBTC", "kucoin": "ITC-BTC"},
        "DNT/BTC": {"binance": "DNTBTC"},
        "ZPT/ETH": {"kucoin": "ZPT-ETH"},
        "BNT/ETH": {"binance": "BNTETH"},
        "BTC/QRK": {"bx": "19"},
        "ETH/USDT": {"binance": "ETHUSDT", "huobi": "ETHUSDT", "kucoin": "ETH-USDT"},
        "EDO/ETH": {"binance": "EDOETH"},
        "CHAT/BTC": {"binance": "CHATBTC", "huobi": "CHATBTC"},
        "YEE/ETH": {"huobi": "YEEETH"},
        "LOCI/ETH": {"kucoin": "LOCI-ETH"},
        "MTX/ETH": {"huobi": "MTXETH"},
        "AE/BNB": {"binance": "AEBNB"},
        "PROPY/ETH": {"huobi": "PROPYETH"},
        "SNT/USDT": {"huobi": "SNTUSDT"},
        "APH/NEO": {"kucoin": "APH-NEO"},
        "ADB/BTC": {"kucoin": "ADB-BTC"},
        "LET/ETH": {"huobi": "LETETH"},
        "CXO/ETH": {"kucoin": "CXO-ETH"},
        "RUFF/USDT": {"huobi": "RUFFUSDT"},
        "BCN/ETH": {"binance": "BCNETH"},
        "HAV/BTC": {"kucoin": "HAV-BTC"},
        "CMT/BTC": {"binance": "CMTBTC", "huobi": "CMTBTC"},
        "NAV/BNB": {"binance": "NAVBNB"},
        "HST/ETH": {"kucoin": "HST-ETH"},
        "TIME/ETH": {"kucoin": "TIME-ETH"}
    },
    kucoin: {
        "SNC-BTC": "SNC/BTC",
        "ETC-KCS": "ETC/KCS",
        "EOS-ETH": "EOS/ETH",
        "POLY-ETH": "POLY/ETH",
        "PRL-BTC": "PRL/BTC",
        "POLY-BTC": "POLY/BTC",
        "LOOM-BTC": "LOOM/BTC",
        "UTK-ETH": "UTK/ETH",
        "ZIL-ETH": "ZIL/ETH",
        "LTC-USDT": "LTC/USDT",
        "R-ETH": "R/ETH",
        "AION-BTC": "AION/BTC",
        "WPR-BTC": "WPR/BTC",
        "TFL-BTC": "TFL/BTC",
        "CHP-BTC": "CHP/BTC",
        "BOS-ETH": "BOS/ETH",
        "LTC-NEO": "LTC/NEO",
        "DAT-ETH": "DAT/ETH",
        "GAS-KCS": "GAS/KCS",
        "SNT-BTC": "SNT/BTC",
        "ETC-ETH": "ETC/ETH",
        "EOS-USDT": "EOS/USDT",
        "CAPP-BTC": "CAPP/BTC",
        "LYM-USDT": "LYM/USDT",
        "HPB-BTC": "HPB/BTC",
        "KCS-USDT": "KCS/USDT",
        "RDN-ETH": "RDN/ETH",
        "LTC-BTC": "LTC/BTC",
        "DADI-BTC": "DADI/BTC",
        "NEBL-BTC": "NEBL/BTC",
        "CXO-ETH": "CXO/ETH",
        "APH-BTC": "APH/BTC",
        "SRN-ETH": "SRN/ETH",
        "KCS-BTC": "KCS/BTC",
        "BTG-BTC": "BTG/BTC",
        "TNC-ETH": "TNC/ETH",
        "ADB-ETH": "ADB/ETH",
        "CS-USDT": "CS/USDT",
        "REQ-ETH": "REQ/ETH",
        "ETH-BTC": "ETH/BTC",
        "COFI-ETH": "COFI/ETH",
        "EOS-NEO": "EOS/NEO",
        "UKG-BTC": "UKG/BTC",
        "DBC-ETH": "DBC/ETH",
        "BTM-BTC": "BTM/BTC",
        "WAN-ETH": "WAN/ETH",
        "DTA-BTC": "DTA/BTC",
        "HAV-ETH": "HAV/ETH",
        "LOOM-ETH": "LOOM/ETH",
        "CAT-ETH": "CAT/ETH",
        "BHC-BTC": "BHC/BTC",
        "STK-ETH": "STK/ETH",
        "AION-ETH": "AION/ETH",
        "COFI-BTC": "COFI/BTC",
        "SPF-ETH": "SPF/ETH",
        "HKN-ETH": "HKN/ETH",
        "MWAT-BTC": "MWAT/BTC",
        "ENJ-ETH": "ENJ/ETH",
        "EOS-BTC": "EOS/BTC",
        "BTG-ETH": "BTG/ETH",
        "TIO-BTC": "TIO/BTC",
        "INS-BTC": "INS/BTC",
        "DNA-BTC": "DNA/BTC",
        "SNM-BTC": "SNM/BTC",
        "QLC-ETH": "QLC/ETH",
        "DGB-ETH": "DGB/ETH",
        "INS-ETH": "INS/ETH",
        "SHL-ETH": "SHL/ETH",
        "POLL-ETH": "POLL/ETH",
        "RHOC-ETH": "RHOC/ETH",
        "GAS-NEO": "GAS/NEO",
        "MOD-ETH": "MOD/ETH",
        "TEL-BTC": "TEL/BTC",
        "LOCI-BTC": "LOCI/BTC",
        "TKY-BTC": "TKY/BTC",
        "MAN-BTC": "MAN/BTC",
        "DGB-BTC": "DGB/BTC",
        "DRGN-NEO": "DRGN/NEO",
        "PLAY-BTC": "PLAY/BTC",
        "SPF-BTC": "SPF/BTC",
        "ELEC-BTC": "ELEC/BTC",
        "PRL-NEO": "PRL/NEO",
        "TKY-USDT": "TKY/USDT",
        "POE-ETH": "POE/ETH",
        "ONION-BTC": "ONION/BTC",
        "XRB-ETH": "XRB/ETH",
        "CVC-BTC": "CVC/BTC",
        "STK-BTC": "STK/BTC",
        "PPT-ETH": "PPT/ETH",
        "AXP-ETH": "AXP/ETH",
        "BNTY-BTC": "BNTY/BTC",
        "ZIL-BTC": "ZIL/BTC",
        "PBL-BTC": "PBL/BTC",
        "TOMO-ETH": "TOMO/ETH",
        "GAT-BTC": "GAT/BTC",
        "NEBL-ETH": "NEBL/ETH",
        "DASH-ETH": "DASH/ETH",
        "PARETO-ETH": "PARETO/ETH",
        "BNTY-ETH": "BNTY/ETH",
        "KICK-ETH": "KICK/ETH",
        "HSR-BTC": "HSR/BTC",
        "ACAT-BTC": "ACAT/BTC",
        "OPEN-ETH": "OPEN/ETH",
        "EXY-BTC": "EXY/BTC",
        "DRGN-USDT": "DRGN/USDT",
        "BCH-KCS": "BCH/KCS",
        "NULS-ETH": "NULS/ETH",
        "EXY-ETH": "EXY/ETH",
        "ACAT-ETH": "ACAT/ETH",
        "ETN-BTC": "ETN/BTC",
        "CAN-ETH": "CAN/ETH",
        "BCD-BTC": "BCD/BTC",
        "MANA-BTC": "MANA/BTC",
        "UKG-ETH": "UKG/ETH",
        "RPX-NEO": "RPX/NEO",
        "ELF-ETH": "ELF/ETH",
        "CVC-ETH": "CVC/ETH",
        "XRB-USDT": "XRB/USDT",
        "QTUM-BTC": "QTUM/BTC",
        "LYM-BTC": "LYM/BTC",
        "J8T-ETH": "J8T/ETH",
        "JNT-ETH": "JNT/ETH",
        "EBTC-BTC": "EBTC/BTC",
        "XLR-ETH": "XLR/ETH",
        "TEL-ETH": "TEL/ETH",
        "ABT-BTC": "ABT/BTC",
        "ONT-BTC": "ONT/BTC",
        "GAT-ETH": "GAT/ETH",
        "BCD-ETH": "BCD/ETH",
        "AIX-BTC": "AIX/BTC",
        "MTN-ETH": "MTN/ETH",
        "WAX-BTC": "WAX/BTC",
        "RPX-ETH": "RPX/ETH",
        "AGI-ETH": "AGI/ETH",
        "ELF-BTC": "ELF/BTC",
        "SPHTX-ETH": "SPHTX/ETH",
        "BPT-BTC": "BPT/BTC",
        "BRD-BTC": "BRD/BTC",
        "MANA-ETH": "MANA/ETH",
        "DBC-NEO": "DBC/NEO",
        "ETH-USDT": "ETH/USDT",
        "NEO-USDT": "NEO/USDT",
        "FLIXX-ETH": "FLIXX/ETH",
        "HAV-USDT": "HAV/USDT",
        "DNA-ETH": "DNA/ETH",
        "ACT-BTC": "ACT/BTC",
        "REQ-BTC": "REQ/BTC",
        "ABT-ETH": "ABT/ETH",
        "TIME-ETH": "TIME/ETH",
        "ARY-BTC": "ARY/BTC",
        "AXP-BTC": "AXP/BTC",
        "DAT-BTC": "DAT/BTC",
        "FLIXX-BTC": "FLIXX/BTC",
        "ONT-NEO": "ONT/NEO",
        "TIO-ETH": "TIO/ETH",
        "DATX-ETH": "DATX/ETH",
        "BCPT-BTC": "BCPT/BTC",
        "OCN-BTC": "OCN/BTC",
        "AIX-ETH": "AIX/ETH",
        "JNT-BTC": "JNT/BTC",
        "ACT-ETH": "ACT/ETH",
        "SHL-BTC": "SHL/BTC",
        "BCPT-ETH": "BCPT/ETH",
        "HST-BTC": "HST/BTC",
        "TNC-BTC": "TNC/BTC",
        "DOCK-BTC": "DOCK/BTC",
        "KEY-BTC": "KEY/BTC",
        "IHT-ETH": "IHT/ETH",
        "MTH-BTC": "MTH/BTC",
        "KCS-ETH": "KCS/ETH",
        "HST-ETH": "HST/ETH",
        "POWR-ETH": "POWR/ETH",
        "SPHTX-BTC": "SPHTX/BTC",
        "CHP-ETH": "CHP/ETH",
        "TRAC-BTC": "TRAC/BTC",
        "ARN-ETH": "ARN/ETH",
        "MAN-ETH": "MAN/ETH",
        "POLL-BTC": "POLL/BTC",
        "DASH-BTC": "DASH/BTC",
        "TIME-BTC": "TIME/BTC",
        "PURA-BTC": "PURA/BTC",
        "NEO-KCS": "NEO/KCS",
        "XAS-ETH": "XAS/ETH",
        "KNC-BTC": "KNC/BTC",
        "IOST-ETH": "IOST/ETH",
        "UTK-BTC": "UTK/BTC",
        "ARY-ETH": "ARY/ETH",
        "HSR-USDT": "HSR/USDT",
        "WPR-ETH": "WPR/ETH",
        "ETN-ETH": "ETN/ETH",
        "HAV-BTC": "HAV/BTC",
        "GAS-BTC": "GAS/BTC",
        "STX-BTC": "STX/BTC",
        "TFL-ETH": "TFL/ETH",
        "LEND-ETH": "LEND/ETH",
        "MOD-BTC": "MOD/BTC",
        "PPT-BTC": "PPT/BTC",
        "WAN-BTC": "WAN/BTC",
        "EBTC-ETH": "EBTC/ETH",
        "OMG-ETH": "OMG/ETH",
        "APH-NEO": "APH/NEO",
        "BCH-BTC": "BCH/BTC",
        "HPB-ETH": "HPB/ETH",
        "SNC-ETH": "SNC/ETH",
        "ING-BTC": "ING/BTC",
        "DTA-ETH": "DTA/ETH",
        "ELIX-BTC": "ELIX/BTC",
        "SNM-ETH": "SNM/ETH",
        "WTC-BTC": "WTC/BTC",
        "RPX-BTC": "RPX/BTC",
        "CHSB-ETH": "CHSB/ETH",
        "CAN-BTC": "CAN/BTC",
        "HSR-ETH": "HSR/ETH",
        "KICK-BTC": "KICK/BTC",
        "POWR-BTC": "POWR/BTC",
        "TKY-NEO": "TKY/NEO",
        "AMB-ETH": "AMB/ETH",
        "RPX-KCS": "RPX/KCS",
        "XRB-BTC": "XRB/BTC",
        "SUB-ETH": "SUB/ETH",
        "HAT-BTC": "HAT/BTC",
        "DENT-ETH": "DENT/ETH",
        "R-BTC": "R/BTC",
        "STX-ETH": "STX/ETH",
        "BCH-ETH": "BCH/ETH",
        "CHSB-BTC": "CHSB/BTC",
        "IOST-BTC": "IOST/BTC",
        "MTH-ETH": "MTH/ETH",
        "LA-BTC": "LA/BTC",
        "BPT-ETH": "BPT/ETH",
        "TRAC-ETH": "TRAC/ETH",
        "PLAY-ETH": "PLAY/ETH",
        "EVX-ETH": "EVX/ETH",
        "CAG-BTC": "CAG/BTC",
        "ITC-BTC": "ITC/BTC",
        "OCN-ETH": "OCN/ETH",
        "XLR-BTC": "XLR/BTC",
        "SNOV-ETH": "SNOV/ETH",
        "ENJ-BTC": "ENJ/BTC",
        "GLA-ETH": "GLA/ETH",
        "ACT-USDT": "ACT/USDT",
        "DBC-BTC": "DBC/BTC",
        "RDN-BTC": "RDN/BTC",
        "DOCK-ETH": "DOCK/ETH",
        "XAS-BTC": "XAS/BTC",
        "PARETO-BTC": "PARETO/BTC",
        "AMB-BTC": "AMB/BTC",
        "NEO-BTC": "NEO/BTC",
        "LALA-BTC": "LALA/BTC",
        "LALA-ETH": "LALA/ETH",
        "HAT-ETH": "HAT/ETH",
        "ZPT-NEO": "ZPT/NEO",
        "NEO-ETH": "NEO/ETH",
        "ADB-BTC": "ADB/BTC",
        "RHOC-BTC": "RHOC/BTC",
        "CAG-ETH": "CAG/ETH",
        "AGI-BTC": "AGI/BTC",
        "VEN-ETH": "VEN/ETH",
        "BRD-ETH": "BRD/ETH",
        "BTM-ETH": "BTM/ETH",
        "QLC-NEO": "QLC/NEO",
        "KNC-ETH": "KNC/ETH",
        "ZPT-BTC": "ZPT/BTC",
        "SRN-BTC": "SRN/BTC",
        "TOMO-BTC": "TOMO/BTC",
        "SUB-BTC": "SUB/BTC",
        "PAY-ETH": "PAY/ETH",
        "GVT-ETH": "GVT/ETH",
        "DENT-BTC": "DENT/BTC",
        "QLC-BTC": "QLC/BTC",
        "KEY-ETH": "KEY/ETH",
        "POE-BTC": "POE/BTC",
        "SNT-ETH": "SNT/ETH",
        "PRL-ETH": "PRL/ETH",
        "ZPT-ETH": "ZPT/ETH",
        "COV-ETH": "COV/ETH",
        "TKY-ETH": "TKY/ETH",
        "LEND-BTC": "LEND/BTC",
        "FOTA-BTC": "FOTA/BTC",
        "DEB-ETH": "DEB/ETH",
        "IHT-BTC": "IHT/BTC",
        "LTC-ETH": "LTC/ETH",
        "NULS-BTC": "NULS/BTC",
        "CAPP-ETH": "CAPP/ETH",
        "PURA-ETH": "PURA/ETH",
        "FOTA-ETH": "FOTA/ETH",
        "ELEC-ETH": "ELEC/ETH",
        "OPEN-BTC": "OPEN/BTC",
        "CAT-BTC": "CAT/BTC",
        "DEB-BTC": "DEB/BTC",
        "DRGN-BTC": "DRGN/BTC",
        "EVX-BTC": "EVX/BTC",
        "COV-BTC": "COV/BTC",
        "CV-ETH": "CV/ETH",
        "CS-BTC": "CS/BTC",
        "PBL-ETH": "PBL/ETH",
        "CXO-BTC": "CXO/BTC",
        "TNC-NEO": "TNC/NEO",
        "CS-ETH": "CS/ETH",
        "ING-ETH": "ING/ETH",
        "ARN-BTC": "ARN/BTC",
        "DADI-ETH": "DADI/ETH",
        "BOS-BTC": "BOS/BTC",
        "ONT-ETH": "ONT/ETH",
        "PAY-BTC": "PAY/BTC",
        "HKN-BTC": "HKN/BTC",
        "ETC-BTC": "ETC/BTC",
        "CV-BTC": "CV/BTC",
        "GVT-BTC": "GVT/BTC",
        "APH-ETH": "APH/ETH",
        "GLA-BTC": "GLA/BTC",
        "SNOV-BTC": "SNOV/BTC",
        "LOCI-ETH": "LOCI/ETH",
        "BTC-USDT": "BTC/USDT",
        "MWAT-ETH": "MWAT/ETH",
        "WAX-ETH": "WAX/ETH",
        "MTN-BTC": "MTN/BTC",
        "VEN-BTC": "VEN/BTC",
        "DRGN-ETH": "DRGN/ETH",
        "DATX-BTC": "DATX/BTC",
        "QSP-ETH": "QSP/ETH",
        "ELIX-ETH": "ELIX/ETH",
        "OMG-BTC": "OMG/BTC",
        "ITC-ETH": "ITC/ETH",
        "LA-ETH": "LA/ETH",
        "QSP-BTC": "QSP/BTC",
        "BCH-USDT": "BCH/USDT",
        "J8T-BTC": "J8T/BTC",
        "LYM-ETH": "LYM/ETH",
        "ONION-ETH": "ONION/ETH"
    },
    bx: {
        "29": "THB/XZC",
        "28": "THB/EVX",
        "14": "BTC/PND",
        "8": "BTC/ZEC",
        "13": "BTC/HYP",
        "23": "THB/REP",
        "5": "BTC/PPC",
        "15": "BTC/XCN",
        "21": "THB/ETH",
        "20": "ETH/BTC",
        "30": "THB/LTC",
        "27": "THB/BCH",
        "18": "BTC/LEO",
        "11": "BTC/CPT",
        "17": "BTC/XPY",
        "26": "THB/OMG",
        "31": "THB/POW",
        "22": "THB/DAS",
        "1": "THB/BTC",
        "24": "THB/GNO",
        "2": "BTC/LTC",
        "3": "BTC/NMC",
        "7": "BTC/XPM",
        "9": "BTC/ZET",
        "19": "BTC/QRK",
        "4": "BTC/DOG",
        "6": "BTC/FTC",
        "25": "THB/XRP"
    },
    binance: {
        "AIONBNB": "AION/BNB",
        "NANOBNB": "NANO/BNB",
        "TRIGBTC": "TRIG/BTC",
        "REPBNB": "REP/BNB",
        "APPCETH": "APPC/ETH",
        "POEBTC": "POE/BTC",
        "BATETH": "BAT/ETH",
        "ENGBTC": "ENG/BTC",
        "IOSTBTC": "IOST/BTC",
        "NULSBTC": "NULS/BTC",
        "ELFETH": "ELF/ETH",
        "DGDETH": "DGD/ETH",
        "STEEMBTC": "STEEM/BTC",
        "BCDETH": "BCD/ETH",
        "WTCBTC": "WTC/BTC",
        "GTOBNB": "GTO/BNB",
        "NEOBTC": "NEO/BTC",
        "ADABNB": "ADA/BNB",
        "BTSETH": "BTS/ETH",
        "ENJBTC": "ENJ/BTC",
        "SYSBTC": "SYS/BTC",
        "ZENBNB": "ZEN/BNB",
        "LUNETH": "LUN/ETH",
        "LTCETH": "LTC/ETH",
        "ADXBTC": "ADX/BTC",
        "WABIETH": "WABI/ETH",
        "LINKBTC": "LINK/BTC",
        "POAETH": "POA/ETH",
        "OMGBTC": "OMG/BTC",
        "LTCBNB": "LTC/BNB",
        "PPTBTC": "PPT/BTC",
        "OAXBTC": "OAX/BTC",
        "RDNBTC": "RDN/BTC",
        "BNTETH": "BNT/ETH",
        "XEMBNB": "XEM/BNB",
        "CMTBTC": "CMT/BTC",
        "OSTETH": "OST/ETH",
        "EDOETH": "EDO/ETH",
        "VIBETH": "VIB/ETH",
        "LINKETH": "LINK/ETH",
        "CNDBNB": "CND/BNB",
        "WTCETH": "WTC/ETH",
        "IOTAETH": "IOTA/ETH",
        "XVGETH": "XVG/ETH",
        "BTSBTC": "BTS/BTC",
        "QTUMUSDT": "QTUM/USDT",
        "TUSDBNB": "TUSD/BNB",
        "NEBLBNB": "NEBL/BNB",
        "ETCBTC": "ETC/BTC",
        "ENJETH": "ENJ/ETH",
        "SYSBNB": "SYS/BNB",
        "NEOUSDT": "NEO/USDT",
        "GNTETH": "GNT/ETH",
        "PIVXETH": "PIVX/ETH",
        "REQBTC": "REQ/BTC",
        "MDABTC": "MDA/BTC",
        "IOTABNB": "IOTA/BNB",
        "NULSBNB": "NULS/BNB",
        "XMRETH": "XMR/ETH",
        "DLTBNB": "DLT/BNB",
        "TNBETH": "TNB/ETH",
        "RPXETH": "RPX/ETH",
        "QLCBTC": "QLC/BTC",
        "POABTC": "POA/BTC",
        "POWRETH": "POWR/ETH",
        "LOOMETH": "LOOM/ETH",
        "GXSETH": "GXS/ETH",
        "XZCBNB": "XZC/BNB",
        "AEETH": "AE/ETH",
        "GXSBTC": "GXS/BTC",
        "BTGBTC": "BTG/BTC",
        "NCASHBTC": "NCASH/BTC",
        "CDTETH": "CDT/ETH",
        "STORJBTC": "STORJ/BTC",
        "RCNETH": "RCN/ETH",
        "STORMBTC": "STORM/BTC",
        "BLZETH": "BLZ/ETH",
        "EVXBTC": "EVX/BTC",
        "XZCETH": "XZC/ETH",
        "SYSETH": "SYS/ETH",
        "LENDETH": "LEND/ETH",
        "QTUMETH": "QTUM/ETH",
        "VIABTC": "VIA/BTC",
        "FUELETH": "FUEL/ETH",
        "TRXETH": "TRX/ETH",
        "DLTBTC": "DLT/BTC",
        "QTUMBTC": "QTUM/BTC",
        "POEETH": "POE/ETH",
        "ELFBTC": "ELF/BTC",
        "WPRBTC": "WPR/BTC",
        "GRSBTC": "GRS/BTC",
        "NULSETH": "NULS/ETH",
        "VIBEBTC": "VIBE/BTC",
        "NEBLBTC": "NEBL/BTC",
        "ZENBTC": "ZEN/BTC",
        "XLMBTC": "XLM/BTC",
        "BQXETH": "BQX/ETH",
        "BCCBTC": "BCC/BTC",
        "ETHUSDT": "ETH/USDT",
        "CHATBTC": "CHAT/BTC",
        "SUBETH": "SUB/ETH",
        "ZECETH": "ZEC/ETH",
        "DNTBTC": "DNT/BTC",
        "WANETH": "WAN/ETH",
        "LTCUSDT": "LTC/USDT",
        "MTLBTC": "MTL/BTC",
        "ZILETH": "ZIL/ETH",
        "ASTBTC": "AST/BTC",
        "LOOMBNB": "LOOM/BNB",
        "MODBTC": "MOD/BTC",
        "BQXBTC": "BQX/BTC",
        "CMTETH": "CMT/ETH",
        "RPXBNB": "RPX/BNB",
        "CDTBTC": "CDT/BTC",
        "SKYBTC": "SKY/BTC",
        "QTUMBNB": "QTUM/BNB",
        "ZENETH": "ZEN/ETH",
        "DLTETH": "DLT/ETH",
        "RDNBNB": "RDN/BNB",
        "MTLETH": "MTL/ETH",
        "FUNBTC": "FUN/BTC",
        "ADAUSDT": "ADA/USDT",
        "BCNBNB": "BCN/BNB",
        "NAVBTC": "NAV/BTC",
        "STRATBTC": "STRAT/BTC",
        "MANAETH": "MANA/ETH",
        "ADAETH": "ADA/ETH",
        "ICXETH": "ICX/ETH",
        "BCCETH": "BCC/ETH",
        "ADXBNB": "ADX/BNB",
        "REPBTC": "REP/BTC",
        "PIVXBTC": "PIVX/BTC",
        "ONTETH": "ONT/ETH",
        "RPXBTC": "RPX/BTC",
        "APPCBNB": "APPC/BNB",
        "STORJETH": "STORJ/ETH",
        "NEOBNB": "NEO/BNB",
        "SALTBTC": "SALT/BTC",
        "RLCETH": "RLC/ETH",
        "BNBUSDT": "BNB/USDT",
        "ARNETH": "ARN/ETH",
        "MCOBTC": "MCO/BTC",
        "BLZBTC": "BLZ/BTC",
        "NCASHETH": "NCASH/ETH",
        "STEEMETH": "STEEM/ETH",
        "XRPUSDT": "XRP/USDT",
        "VIBEETH": "VIBE/ETH",
        "MTHBTC": "MTH/BTC",
        "ETHBTC": "ETH/BTC",
        "OAXETH": "OAX/ETH",
        "FUELBTC": "FUEL/BTC",
        "LRCBTC": "LRC/BTC",
        "OMGETH": "OMG/ETH",
        "NCASHBNB": "NCASH/BNB",
        "XLMETH": "XLM/ETH",
        "NEOETH": "NEO/ETH",
        "BRDBNB": "BRD/BNB",
        "ADXETH": "ADX/ETH",
        "ARNBTC": "ARN/BTC",
        "EDOBTC": "EDO/BTC",
        "MTHETH": "MTH/ETH",
        "LRCETH": "LRC/ETH",
        "TRIGBNB": "TRIG/BNB",
        "CLOAKBTC": "CLOAK/BTC",
        "MCOBNB": "MCO/BNB",
        "VIABNB": "VIA/BNB",
        "VIBBTC": "VIB/BTC",
        "DASHBTC": "DASH/BTC",
        "INSETH": "INS/ETH",
        "EOSETH": "EOS/ETH",
        "GTOETH": "GTO/ETH",
        "POWRBTC": "POWR/BTC",
        "STRATETH": "STRAT/ETH",
        "POWRBNB": "POWR/BNB",
        "BTGETH": "BTG/ETH",
        "DNTETH": "DNT/ETH",
        "LOOMBTC": "LOOM/BTC",
        "ARKETH": "ARK/ETH",
        "MODETH": "MOD/ETH",
        "MCOETH": "MCO/ETH",
        "XEMETH": "XEM/ETH",
        "SNGLSBTC": "SNGLS/BTC",
        "GNTBTC": "GNT/BTC",
        "KMDETH": "KMD/ETH",
        "SKYETH": "SKY/ETH",
        "HSRETH": "HSR/ETH",
        "KNCETH": "KNC/ETH",
        "BNBETH": "BNB/ETH",
        "POABNB": "POA/BNB",
        "LTCBTC": "LTC/BTC",
        "ZILBTC": "ZIL/BTC",
        "WPRETH": "WPR/ETH",
        "XMRBTC": "XMR/BTC",
        "ZRXBTC": "ZRX/BTC",
        "OSTBTC": "OST/BTC",
        "BNBBTC": "BNB/BTC",
        "LENDBTC": "LEND/BTC",
        "REPETH": "REP/ETH",
        "STORMETH": "STORM/ETH",
        "CNDETH": "CND/ETH",
        "NAVETH": "NAV/ETH",
        "WABIBTC": "WABI/BTC",
        "MDAETH": "MDA/ETH",
        "PIVXBNB": "PIVX/BNB",
        "GNTBNB": "GNT/BNB",
        "XEMBTC": "XEM/BTC",
        "EVXETH": "EVX/ETH",
        "ENGETH": "ENG/ETH",
        "REQETH": "REQ/ETH",
        "BRDETH": "BRD/ETH",
        "BCCUSDT": "BCC/USDT",
        "QSPBNB": "QSP/BNB",
        "GASBTC": "GAS/BTC",
        "APPCBTC": "APPC/BTC",
        "BCPTBNB": "BCPT/BNB",
        "XRPETH": "XRP/ETH",
        "TNBBTC": "TNB/BTC",
        "VIAETH": "VIA/ETH",
        "SNTBTC": "SNT/BTC",
        "IOTABTC": "IOTA/BTC",
        "BATBTC": "BAT/BTC",
        "ONTBNB": "ONT/BNB",
        "QLCBNB": "QLC/BNB",
        "GVTBTC": "GVT/BTC",
        "VENBNB": "VEN/BNB",
        "ZRXETH": "ZRX/ETH",
        "IOSTETH": "IOST/ETH",
        "BATBNB": "BAT/BNB",
        "WINGSETH": "WINGS/ETH",
        "AMBBNB": "AMB/BNB",
        "STEEMBNB": "STEEM/BNB",
        "SUBBTC": "SUB/BTC",
        "BRDBTC": "BRD/BTC",
        "OSTBNB": "OST/BNB",
        "AIONBTC": "AION/BTC",
        "AMBBTC": "AMB/BTC",
        "NEBLETH": "NEBL/ETH",
        "WINGSBTC": "WINGS/BTC",
        "XVGBTC": "XVG/BTC",
        "WAVESETH": "WAVES/ETH",
        "RLCBTC": "RLC/BTC",
        "BNTBTC": "BNT/BTC",
        "RCNBNB": "RCN/BNB",
        "GVTETH": "GVT/ETH",
        "WAVESBTC": "WAVES/BTC",
        "TUSDETH": "TUSD/ETH",
        "XZCBTC": "XZC/BTC",
        "CMTBNB": "CMT/BNB",
        "DGDBTC": "DGD/BTC",
        "SKYBNB": "SKY/BNB",
        "BCNBTC": "BCN/BTC",
        "FUNETH": "FUN/ETH",
        "YOYOBNB": "YOYO/BNB",
        "TRIGETH": "TRIG/ETH",
        "XRPBTC": "XRP/BTC",
        "EOSBTC": "EOS/BTC",
        "SNTETH": "SNT/ETH",
        "NANOETH": "NANO/ETH",
        "YOYOETH": "YOYO/ETH",
        "WANBTC": "WAN/BTC",
        "YOYOBTC": "YOYO/BTC",
        "CNDBTC": "CND/BTC",
        "AEBNB": "AE/BNB",
        "AEBTC": "AE/BTC",
        "LSKETH": "LSK/ETH",
        "TRXBTC": "TRX/BTC",
        "RCNBTC": "RCN/BTC",
        "BCNETH": "BCN/ETH",
        "DASHETH": "DASH/ETH",
        "GRSETH": "GRS/ETH",
        "BTSBNB": "BTS/BNB",
        "ICNETH": "ICN/ETH",
        "LSKBNB": "LSK/BNB",
        "XLMBNB": "XLM/BNB",
        "ADABTC": "ADA/BTC",
        "VENETH": "VEN/ETH",
        "CLOAKETH": "CLOAK/ETH",
        "KMDBTC": "KMD/BTC",
        "QSPETH": "QSP/ETH",
        "KNCBTC": "KNC/BTC",
        "RDNETH": "RDN/ETH",
        "WAVESBNB": "WAVES/BNB",
        "TNTBTC": "TNT/BTC",
        "QSPBTC": "QSP/BTC",
        "TUSDBTC": "TUSD/BTC",
        "WTCBNB": "WTC/BNB",
        "VENBTC": "VEN/BTC",
        "BCDBTC": "BCD/BTC",
        "BTCUSDT": "BTC/USDT",
        "SNGLSETH": "SNGLS/ETH",
        "SNMETH": "SNM/ETH",
        "MANABTC": "MANA/BTC",
        "ICXBTC": "ICX/BTC",
        "QLCETH": "QLC/ETH",
        "BCPTBTC": "BCPT/BTC",
        "ETCETH": "ETC/ETH",
        "CHATETH": "CHAT/ETH",
        "WANBNB": "WAN/BNB",
        "BCPTETH": "BCPT/ETH",
        "ASTETH": "AST/ETH",
        "ZILBNB": "ZIL/BNB",
        "LSKBTC": "LSK/BTC",
        "BLZBNB": "BLZ/BNB",
        "PPTETH": "PPT/ETH",
        "BCCBNB": "BCC/BNB",
        "LUNBTC": "LUN/BTC",
        "WABIBNB": "WABI/BNB",
        "STORMBNB": "STORM/BNB",
        "TNTETH": "TNT/ETH",
        "INSBTC": "INS/BTC",
        "SNMBTC": "SNM/BTC",
        "SALTETH": "SALT/ETH",
        "ZECBTC": "ZEC/BTC",
        "ICXBNB": "ICX/BNB",
        "AIONETH": "AION/ETH",
        "RLCBNB": "RLC/BNB",
        "NANOBTC": "NANO/BTC",
        "ONTBTC": "ONT/BTC",
        "NAVBNB": "NAV/BNB",
        "ICNBTC": "ICN/BTC",
        "ARKBTC": "ARK/BTC",
        "HSRBTC": "HSR/BTC",
        "GTOBTC": "GTO/BTC",
        "AMBETH": "AMB/ETH"
    }
};

module.exports = symbol;